# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI-CD-angular

on:
  push:
    branches: [ "master" ]

jobs:
  avoid_reduncy:
    runs-on: ubuntu-22.04
    steps: 
      - name: Cancela build previos redundantes
        uses: styfle/cancel-workflow-action@0.12.0
        with: 
          access_token: ${{ github.token }}
  install:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        # preconfig de node
      - uses: actions/setup-node@v3.8.1
        with:
          cache: 'npm'
          node-version: '18.18.0'
      - name: Instalando dependencias
        # npm ci es especifico de npm para instalar con cicd  
        run: npm ci
  build:
    needs: [install] 
    runs-on: ubuntu-22.04
    steps:
        # verifica cambios
      - name: Verifica cambios 
        uses: actions/checkout@v3
        #ultimo commit para mas velocidad
        with:
          fetch-depth: 0
        # preconfig de node
      - name: Instalando node  
        uses: actions/setup-node@v3.8.1
        with:
          cache: 'npm'
          node-version: '18.18.0'
      - name: Instalando dependencias
        # npm ci es especifico de npm para instalar con cicd  
        run: npm ci
      - name: Build aplicacion
        run: npm run build  
      - name: Pasar build a siguiente job
        uses: actions/upload-artifact@v3.1.3
        with:
           name: dist
           path: dist
  # test:
  #   needs: [build]
  #   runs-on: ubuntu-22.04
  #   steps:
  #     # verifica cambios
  #   - name: Verifica cambios 
  #     uses: actions/checkout@v3
  #     #ultimo commit para mas velocidad
  #     with:
  #       fetch-depth: 0
  #     # preconfig de node
  #   - name: Instalando node  
  #     uses: actions/setup-node@v3.8.1
  #     with:
  #       cache: 'npm'
  #       node-version: '18.18.0'
  #   - name: Instalando dependencias
  #     # npm ci es especifico de npm para instalar con cicd  
  #     run: npm ci
  #   - name: Obteniendo build anterior
  #     uses: actions/download-artifact@v2.1.1
  #     with:
  #       name: dist
  #       path: dist
  #   - name: Corriendo tests
  #     #run: npm test
  #     run: npm test -- --browsers=ChromeHeadless --watch=false
  
  deploy-app-vps:
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          # port: ${{ secrets.PORT }}
          script: |
            whoami
            ls

  # deploy-app-vps:
  #   needs: [build]
  #   runs-on: self-hosted
  #   steps:
  #     - name: Obteniendo build anterior
  #       uses: actions/download-artifact@v2.1.1
  #       with:
  #         name: dist
  #         path: dist
  #     - uses: actions/checkout@v3
  #     # - run: docker compose up -d --build  
  #     - run: docker cp dist/test-deploy/. angular-v1:/usr/share/nginx/html
  

